### PR TITLE
switch to loaderUtils.getOptions

### LINKED ISSUE #655: Fix loader-utils warning
Hi everyone,

Webpack 2 displays a warning for loaders using `parseQuery` instead of the new `getOptions`. Please have a look at https://github.com/webpack/loader-utils/issues/56 for more information.

I'll try to create a PR in the upcoming weeks but I don't promise anything.

Thanks

### LINKED ISSUE #727: html-webpack-plugins and  loader-utils
webpack bundle an error 
```
Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
```
who can tell me why???

### PR DESCRIPTION
**Pull request by alacroix**
Hi,

Following the issue https://github.com/jantimon/html-webpack-plugin/issues/655, I replace usage of `parseQuery` with `getOptions`.

I also updated the dependency `loader-utils` to its last stable version `1.1.0`.

 Thanks

-----
closes #655
closes #727

### CODE REVIEW

**Comment by jantimon** [comment]
Will this still be compatible with webpack 1 or projects which use a older loader-utils version?

**Comment by alacroix** [comment]
According to [loader-utils changelog](https://github.com/webpack/loader-utils/releases), there are two breaking changes from `^0.2.16` to `'^1.1.0'`:
- Removed node 0.10 and 0.12 support (according to the PR https://github.com/jantimon/html-webpack-plugin/pull/642, it's also planned for this project)
- Replaced `parseQuery` with `getOptions`

Everything should be OK with Webpack 1 projects.
However, it may not work with projects using `loader-utils` with a version older than `'^1.0.0'`.

**Comment by mastilver** [comment]
@alacroix If you could do a rebase on master, that would be awesome as we will be 100% confident it's working for both webpack 1 and 2

**Comment by alacroix** [comment]
@mastilver it's rebased 👍

**Comment by jantimon** [comment]
cool we should merge it into 3.x version as 2.x works for node 0.10.x

**Comment by alacroix** [comment]
@jantimon since the commit 9b272cfb2bccee98bbe8438c817c4207a0a3cb71, the branch `master`  considers node versions `0.10` and `0.12` as deprecated, no ?

**Comment by jantimon** [comment]
Removing a node version is a breaking change so we can't merge it into 2.x

**Comment by mastilver** [comment]
@jantimon I *think* what @alacroix was saying is that it's not their commit which removed the node version, it's  https://github.com/jantimon/html-webpack-plugin/commit/9b272cfb2bccee98bbe8438c817c4207a0a3cb71 which is already in `master` 

BTW the only reason I removed those from travis was because of yarn, so `html-webpack-plugin` is potentially still working on node@0.10 and 0.12

And TBH, I don't think we should care about those users as 0.12 has been deprecated for 6 months but I understand why you care about them ;)

**Comment by mastilver** [comment]
> I re-triggered your build, and tests are passing for webpack@1 on node>=4

This is the build I mention: https://travis-ci.org/jantimon/html-webpack-plugin/builds/229069720

it's only failing because it's failing back to `npm` and somehow `npm` doesn't install the `semistandard` the right way so it fails
At least that's what I understand

**Comment by jantimon** [comment]
This plugin follows the versioning from NPM which is the [semantic versioning model](http://semver.org/).

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.

So as this change would not be fully compatible it would be a MAJOR version jump and we are not allowed to merge it into 2.x but only in 3.x upwards.

**Comment by mastilver** [comment]
@jantimon Sorry my bad, I didn't realise they made `loader-utils` explicitly incompatible with those version

ref: https://github.com/webpack/loader-utils/commit/3499242a17e8e49fd13a169c9c369f12b2890f84#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by alacroix** [comment]
@jantimon @mastilver so I rebase on `version-3.x` and it will be okay?

**Comment by mastilver** [comment]
@alacroix Yes please 👍

**Comment by cristianoliveira** [comment]
Hey guys. Any update on this?

**Comment by CarbonFactory** [comment]
Can someone please update when this will be pushed ? Its still using parseQuery which is breaking my build. For now, I've manually replace it with  `options = loaderUtils.getOptions(this);`

**Comment by janpe** [comment]
@jantimon @mastilver where are we with this one? What are the steps required to get this merged and released?

**Comment by CarbonFactory** [comment]
Still waiting for this commit to go through. Could someone kindly look into it? 
Thank you !

**Comment by jantimon** [comment]
Merged into the  https://github.com/jantimon/html-webpack-plugin/tree/webpack-4

**Pull request closed without merging**
