### PR TITLE
fix "Multiple entry points -> multiple html outputs webpack rebuild very slow #724"

### PR DESCRIPTION
**Pull request by daifee**
# issues 724
https://github.com/jantimon/html-webpack-plugin/issues/724

### CODE REVIEW

**Comment by mastilver** [comment]
Thank you for having a go at this issue :)

But I think the best way to solve that issue would be that `html-webpack-plugin` takes an array of config

So rather that instantiate multiple plugins, we would only have one. How does that sounds to you?

Also tests would be awesome! ;)

**Comment by daifee** [comment]
"html-webpack-plugin takes an array of config" can not solve this issue, The root of this issue is cache.

when a file has been changed, `compiler` will recompile and trigger `plugin('make', cb)`, then `html-webpack-plugin` will create new `childCompiler`, and run `compile` for all html. it is slow.

you should avoid create new `childCompiler`, when the html has not been changed.

**Comment by daifee** [comment]
can you merge the pr, and publish a feature fix version?

**Comment by loopArray** [comment]
这个确实减少了很多的编译时间，之前11个页面更新其中的一个就需要全部编译，花40s左右，现在基本上6s就行了，但是还有一个问题，就是我更新了index.pug仍然会产生很多次的编译。不知道是不是配置的问题。

This is really a lot of compilation time, before 11 pages to update one of them need to compile all, spend 40s or so, now basically 6s on the line, but there is a problem that I updated the index.pug will still produce a lot Compile time. Do not know if the configuration is not the problem.

image

**Comment by kidneyleung** [comment]
@loopArray It is recommended to send configuration, my project test did not appear this situation

**Comment by loopArray** [comment]
My fault, just debugging again, I want to find a place to cry for a while! Traversed again when the local template file, nested loops two times, and this bug actually always existed, I did not find and I was looking for reasons why html-webpack-plugin multiple html so slow.
image

**Comment by jinker** [comment]
@loopArray 我也遇到类似问题，你可以看看这个pr可不可以解决 #802

**Comment by mastilver** [comment]
> @loopArray 我也遇到类似问题，你可以看看这个pr可不可以解决 #802

@jinker I don't mind a few words in a foreign language (just to say hi ;) ), but please keep the conversation in English please

**Comment by mastilver** [comment]
@daifee I'm closing this in flavor of #802 as I find the code simpler and it doesn't add a new variable

Let me know if you disagree! :)

**Comment by daifee** [comment]
@jinker @mastilver  i also tried to do so, and it only reduce 50% time(at my project, recompilation takes 20s).

at my project, the task of compile template is very complex, so `childCompiler.compileTemplate()` is slow. multiple pages will take long time.

the template has not been changed, it should not be recompilated.

**Comment by mastilver** [comment]
@daifee Correct me if I'm wrong but this doesn't to do with multiple pages... It's a caching issue (#680) and it's just because you have multiple pages you get hit by that more heavily than others

**Comment by daifee** [comment]
@mastilver I think so, my project is more heavily. i has forked html-webpack-plugin, and published html-webpack-plugin-for-multihtml to solve my issue.

**Comment by daifee** [comment]
@mastilver Thanks your feedback.

**Comment by limerickgds** [comment]
@mastilver can you publish new version? i also have this issue

**Comment by xilin** [comment]
@daifee Thanks for your work! Using your fork make our project's build time reduce from 10s -> 0.8s. 

Could you share the profile experience on how to locate the time consuming part in webpack building? I tried to use `--progress` and ` --profile`, but the only thing I can tell is that `asset optimization` phase is slow.

**Comment by qiming-kooboo** [comment]
@daifee 
OMG... I really want to say love you so much...
This issue distracting our dev for a long time. 
Finally, it is resolved by your Repo.
Our project rebuild time reduced from 30+s => 1s..

**Comment by daifee** [comment]
@xilin view the source code of html-webpack-plugin.

**Pull request closed without merging**
