### PR TITLE
fix ie11 css caching

### PR DESCRIPTION
**Pull request by seva-ask**
fix for #726

### CODE REVIEW

**Comment by mastilver** [comment]
Hi @seva-ask thank you for the PR

Just need to check with @jantimon if it's really something we need... For two reason:
- it's fixable by adding `Content-Type` on the server side
- it's not on the specs

**Comment by mastilver** [comment]
Oh, and also would you mind adding test ;)

**Comment by richriscunha** [comment]
@mastilver,

I'm curious to know where this stands, if you could please advise.

**Comment by jantimon** [comment]
Please move this feature into a plugin.
The problem happens for js

**Comment by vudduu** [comment]
The commit also will need changes on unit tests to be applied.

For example next unit test will fail.
https://github.com/jantimon/html-webpack-plugin/blob/efbd3525a18bee03a0c8c3899d264a14f2945d85/spec/BasicSpec.js#L479

**Pull request closed without merging**
