### PR TITLE
Fix ProcessedOptions.filename type

### LINKED ISSUE #1552: Interface 'Options' incorrectly extends interface 'Partial<ProcessedOptions>'
Hi, with `5.0.0-alpha.10` and typescript 4.0.5 I'm getting this:

```
node_modules/html-webpack-plugin/typings.d.ts:36:13 - error TS2430: Interface 'Options' incorrectly extends interface 'Partial<ProcessedOptions>'.
  Types of property 'filename' are incompatible.
    Type 'string | ((entryName: string) => string)' is not assignable to type 'string'.
      Type '(entryName: string) => string' is not assignable to type 'string'.

36   interface Options extends Partial<ProcessedOptions> {
               ~~~~~~~

```

### PR DESCRIPTION
**Pull request by jscheid**
Closes #1552

### CODE REVIEW

**Comment by jantimon** [comment]
After processing it is only a `string`

**Comment by jantimon** [comment]
What about:

```
 type Options = Partial<ProcessedOptions> & {
    /**
     * The file to write the HTML to.
     * Supports subdirectories eg: `assets/admin.html`
     * [name] will be replaced by the entry name
     * Supports a function to generate the name
     *
     * @default 'index.html'
     */
    filename?: string | ((entryName: string) => string);
  }
```

**Comment by jscheid** [comment]
> Maybe I should flip it the other way round (calculate ProcessedOptions out of Options)

That sounds like the way to go... I'll work off this branch for now and let you find a good long term solution.

**Comment by jantimon** [comment]
Fixed in 5.0.0-alpha.12:

https://github.com/jantimon/html-webpack-plugin/blob/f15f8e5c695781f4f6a18a68b156da6a3dc356f3/typings.d.ts#L29-L162

**Comment by jscheid** [comment]
Nice! 👍

**Pull request closed without merging**
