### PR TITLE
Add Open Graph tags support

### PR DESCRIPTION
**Pull request by mdesilva**

### CODE REVIEW

**Comment by jantimon** [comment]
Isn't this already possible with meta tags?

**Comment by jantimon** [comment]
```js
new HtmlWebpackPlugin({
  // <meta property="og:title" content="The Rock" />
  meta: { "og:title": { property: "og:title", content: "The Rock" } }
})
```

**Comment by mdesilva** [comment]
Yes, it is possible with the meta tag, but the user must nest the tag keys within a redundant key, and must also be familiar with the meta tag keys (property and content). This is error prone and not very user friendly. With these new tags, one only needs to create a single key value pair for each tag they want to generate. Easy.

**Comment by jantimon** [comment]
I understand your point but I would prefer not to to have two properties for meta tags in the options.

**Comment by mdesilva** [comment]
Is there a way that we can put this to a vote/get more feedback on this from additional committers ?

**Comment by jantimon** [comment]
Open Graph was part of the favicons-webpack-plugin but has been removed: https://github.com/itgalaxy/favicons/commit/7f59a2e20c1ed95605df07f496f484c4368de72e

A quick fix might be the following:

```js
const openGraphTags = (tags) => Object.fromEntries(Object.entries(tags).map(([k,v]) => ['og:' + k, {['og:' +k]: v}]));

new HtmlWebpackPlugin({
  // <meta property="og:title" content="The Rock" />
  meta: { 
    ...openGraphTags({ title: 'The Rock' })
  }
})
```

Or the full syntax: 

```
new HtmlWebpackPlugin({
  // <meta property="og:title" content="The Rock" />
  meta: { "og:title": { property: "og:title", content: "The Rock" } }
})
```

**Comment by mdesilva** [comment]
Sorry, what does a different npm package have to do with this repo ?

**Pull request closed without merging**
