### PR TITLE
feat: Allow URL or Data URI favicon

### PR DESCRIPTION
**Pull request by wuwb**
feat: Allow URL or Data URI favicon.

### CODE REVIEW

**Comment by mastilver** [comment]
Did you have a look at: https://github.com/jantimon/favicons-webpack-plugin ?

**Comment by wuwb** [comment]
@mastilver yes, i had looked through favicons-webpack-plugin. but in my project, i use the configs extracted from vue-route and a custom config with favicon to generate html-webpack-plugin configs, if use favicons-webpack-plugin, i have to generate a mapping favicons-webpack-plugin config to each html-webpack-plugin config, and favicons-webpack-plugin didn't providate this feature, it inject the same config to every html-webpack-plugin config.

**Comment by edmorley** [comment]
Might another way to do this, be to have favicon use whatever webpack loader has been declared for the file type is it? ie: Then if `.(ico|...)` have been configured to use url-loader, the favicon will either be inlined as a data URI or as a path to the copied asset, automatically?

**Comment by edmorley** [comment]
(That approach would also solve the "have hash in favicon filename" use-case)

**Pull request closed without merging**
