### PR TITLE
Fix to work with loader-utils ^1.1.0

### PR DESCRIPTION
**Pull request by AaronFriel**
In case no query is provided, return an empty object. This fixes jantimon/html-webpack-plugin#727 without requiring a major semver bump.

### CODE REVIEW

**Comment by amarnathsaha** [comment]
Is it live ?

**Comment by AaronFriel** [comment]
No, this would need to be merged by @jantimon or perhaps another maintainer.

**Comment by amarnathsaha** [comment]
Please merge. @jantimon

**Comment by ineedthekeyboard** [comment]
Please Merge!

**Comment by kkimdev** [comment]
It seems simple and obvious fix, any reason not to be merged?

**Comment by AaronFriel** [comment]
Hi, @jantimon, @mastilver is there a reason this cannot be merged?

**Comment by kkimdev** [comment]
(also pinging another maintainer in case he has bandwidth) @michael-ciniawsky

**Comment by AaronFriel** [comment]
Thank you!

**Pull request merged**
