### PR TITLE
Update to webpack 3

### LINKED ISSUE #699: Add support for Webpack 3
Webpack 3.0-rc was released and this plugin currently doesn't support it.

I haven't tested it yet, so it might be just a question of updating the peerDependency.

### LINKED ISSUE #705: Webpack 3 issue - ExternalModuleFactoryPlugin - 'request' of undefined
Upgrading to webpack 3 generates an error when used with this plugin.

Degrading to webpack 2.x or removing the plugin from config resolves the error.

Note a simular issue here:
https://github.com/jantimon/html-webpack-plugin/issues/596

Note webpack 3 compatibility issue & PR:
https://github.com/jantimon/html-webpack-plugin/issues/699
https://github.com/jantimon/html-webpack-plugin/pull/704

Plugin version:
```
yarn list v0.24.6
└─ html-webpack-plugin@2.28.0
✨  Done in 1.13s.
```
Webpack version:
```
yarn list v0.24.6
└─ webpack@3.0.0
✨  Done in 1.11s.
```

Summarised webpack.config (i've tried a blank plugin config - no change):
```
var webpack = require('webpack');
var path = require('path');
var htmlWebpackPlugin = require('html-webpack-plugin');
var faviconsWebpackPlugin = require('favicons-webpack-plugin');

const root = process.cwd();

module.exports = {
  resolve: {
    extensions: ['.tsx', '.ts', '.js', '.json']
  },
  plugins: [
    ...
    new htmlWebpackPlugin({
      title: 'HiveHub',
      description: 'A mapping platform for software systems',
      filename: 'index.html',
      template: path.join(root, 'src/index.ejs'),
      inject: false,
      appMountId: 'root',
      initialState: 'null',
      initialContent: 'null'
    })
  ],
  module: {
    rules: [
      ...
    ]
  }
};
```

Full stack dump:
```
ERROR in   TypeError: Cannot read property 'request' of undefined

  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [metamap]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleF    actoryPlugin.js:37:33

  - ExternalModuleFactoryPlugin.js:46 next
    [metamap]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleF    actoryPlugin.js:46:8

  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [metamap]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleF    actoryPlugin.js:59:7

  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin    .<anonymous>
    [metamap]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleF    actoryPlugin.js:79:5

  - NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
    [metamap]/[webpack]/lib/NormalModuleFactory.js:246:4

  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall    [metamap]/[webpack]/[tapable]/lib/Tapable.js:196:70

  - NormalModuleFactory.js:230 NormalModuleFactory.create
    [metamap]/[webpack]/lib/NormalModuleFactory.js:230:8

  - Compilation.js:383 Compilation._addModuleChain
    [metamap]/[webpack]/lib/Compilation.js:383:17

  - Compilation.js:465 Compilation.addEntry
    [metamap]/[webpack]/lib/Compilation.js:465:8

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [metamap]/[html-webpack-plugin]/[webpack]/lib/SingleEntryPlug    in.js:22:15

  - Tapable.js:229 Compiler.applyPluginsParallel
    [metamap]/[webpack]/[tapable]/lib/Tapable.js:229:14

  - Compiler.js:505
    [metamap]/[webpack]/lib/Compiler.js:505:8

  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [metamap]/[webpack]/[tapable]/lib/Tapable.js:131:46

  - Compiler.js:498 Compiler.compile
    [metamap]/[webpack]/lib/Compiler.js:498:7

  - Compiler.js:284 Compiler.runAsChild
    [metamap]/[webpack]/lib/Compiler.js:284:7

  - compiler.js:70
    [metamap]/[html-webpack-plugin]/lib/compiler.js:70:19
```

### PR DESCRIPTION
**Pull request by yuffiy**
closes #699 
closes #705

### CODE REVIEW

**Comment by mastilver** [comment]
Thank you for that PR :)

Good call on `EXTRACT_PLUGIN_VERSION`  👍 

Now we just have to wait for: https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/540 and we will be good to go!

**Comment by d3viant0ne** [comment]
@mastilver - `3.0.0-beta.0` is out on npm. Any issues, ping me in Slack or on Twitter. Either will make it to my cell phone.

**Comment by filipesilva** [comment]
@d3viant0ne I can't seem to find `html-webpack-plugin@3.0.0-beta.0` on npm, was it published?

**Comment by mastilver** [comment]
@filipesilva it's `extract-text-webpack-plugin@@3.0.0-beta.0`

**Comment by filipesilva** [comment]
Ah, apologies, I misunderstoord 👍

**Comment by mastilver** [comment]
@yuffiy Do you mind updating your PR to get the latest `extract-text-webpack-plugin`?

I'm unable to do it atm

**Comment by mastilver** [comment]
@yuffiy @d3viant0ne Thank you for your work! :+1: 

@jantimon I let you squash, merge and release that :)

**Comment by jantimon** [comment]
It's full backwards compatible so we can just release it as 2.29 right?

**Comment by mastilver** [comment]
@jantimon Yep, I no tests for webpack@1/2 have been changed, so I would think there is not breaking changes

**Comment by jantimon** [comment]
Why did you remove the following files?
node_modules/html-webpack-plugin/index.js
node_modules/html-webpack-plugin/lib/loader.js

**Comment by jantimon** [comment]
Thank you so much @d3viant0ne @yuffiy @mastilver for your work :) released as 2.29

**Comment by damianobarbati** [comment]
Should this fix the `ERROR in   TypeError: Cannot read property 'request' of undefined` error we currently have with webpack 3?

**Comment by damianobarbati** [comment]
Working combo for me:
```
        "extract-text-webpack-plugin": "3.0.0-beta.3",
        "html-webpack-plugin": "^2.29.0",
        "webpack": "^3.0.0",
```

**Comment by Kingwl** [comment]
it's very helpful to me!

**Comment by yuffiy** [comment]
Thanks all

**Comment by chrisui** [comment]
Just a heads up it'd be good to add a git release tag so it shows up in the github releases page. Took me a while to realise 2.28.0 isn't the latest and was confused for a while! :)

Thanks for the work on this great plugin!

**Comment by mastilver** [comment]
@chrisui done

**Comment by chrisui** [comment]
@mastilver ⭐️

**Pull request merged**
