### PR TITLE
add dll-link-webpack-plugin to readme

### PR DESCRIPTION
**Pull request by clinyong**

### CODE REVIEW

**Comment by mastilver** [comment]
I would expect Dlls to be added to your output html file, no?

Maybe I don't understand what this plugin is really doing

**Comment by clinyong** [comment]
Hi @mastilver 

I added an [example](https://github.com/clinyong/dll-link-webpack-plugin/tree/master/examples/html-webpack-plugin) of using with html-webpack-plugin. 

This plugin helps you to create dll file. And you can use it with or without html-webpack-plugin. But if you uses html-webpack-plugin, it can inject the dll file to the output html file.

**Comment by mastilver** [comment]
So you are saying that it doesn't work with ` webpack.DllReferencePlugin` ?

**Comment by clinyong** [comment]
Yes, the `DllReferencePlugin` must be replaced.

**Pull request closed without merging**
