### PR TITLE
Add placeholder for custom inject position.

### PR DESCRIPTION
**Pull request by mudoo**

### CODE REVIEW

**Comment by jantimon** [comment]
If you need more control of the template please disable the injection mode

**Comment by mudoo** [comment]
@jantimon Sometimes, we just need to keep something below the head tag, if disable the injection mode, and there are many templates in the project, it's too tedious.

**Comment by jantimon** [comment]
I see - but still it doesn't feel right to invent a second template language on top of another.

Right now we are focussing on performance improvements for the next major release.  
However one feature we might also add is to pass the rendered html of the head and body parts.

That way you could place them anywhere in your template.
Would that help?

**Comment by mudoo** [comment]
That will be great. tks.

**Pull request closed without merging**
