### PR TITLE
Added link and description for nomodule-plugin

### PR DESCRIPTION
**Pull request by swimmadude66**
Created a new plugin to help limit executed file size.

### CODE REVIEW

**Comment by jantimon** [comment]
Could you please adjust your plugin to be compatible to the webpack 5 hook system?

https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.5

**Comment by swimmadude66** [comment]
@jantimon I can't seem to find any documentation for how the webpack 5 hooks are any different that the webpack 4 hooks (which this plugin supports).

Do you have a link to somewhere I could learn about the differences so I can add that support?

**Comment by jantimon** [comment]
The html-webpack-plugin has now a static version property:
https://github.com/jantimon/html-webpack-plugin/blob/d65b37d2c588047e0d81a38f4645fcdb3ead0b9e/index.js#L915-L927

The event system was changed to work with the new features.  
The events are the yellow tags on the right side:



More information about the events can be seen here (the yellow tags on the right side are the events)

https://github.com/jantimon/html-webpack-plugin/tree/webpack-4#events


#### `beforeAssetTagGeneration` hook

```
    AsyncSeriesWaterfallHook<{
      assets: {
        publicPath: string,
        js: Array<{string}>,
        css: Array<{string}>,
        favicon?: string | undefined,
        manifest?: string | undefined
      },
      outputName: string,
      plugin: HtmlWebpackPlugin
    }>
```

#### `alterAssetTags` hook

```
    AsyncSeriesWaterfallHook<{
      assetTags: {
        scripts: Array<HtmlTagObject>,
        styles: Array<HtmlTagObject>,
        meta: Array<HtmlTagObject>,
      },
      outputName: string,
      plugin: HtmlWebpackPlugin
    }>
```

#### `alterAssetTagGroups` hook

```
    AsyncSeriesWaterfallHook<{
      headTags: Array<HtmlTagObject | HtmlTagObject>,
      bodyTags: Array<HtmlTagObject | HtmlTagObject>,
      outputName: string,
      plugin: HtmlWebpackPlugin
    }>
```

#### `afterTemplateExecution` hook

```
    AsyncSeriesWaterfallHook<{
      html: string,
      headTags: Array<HtmlTagObject | HtmlTagObject>,
      bodyTags: Array<HtmlTagObject | HtmlTagObject>,
      outputName: string,
      plugin: HtmlWebpackPlugin,
    }>
```

#### `beforeEmit` hook

```
    AsyncSeriesWaterfallHook<{
      html: string,
      outputName: string,
      plugin: HtmlWebpackPlugin,
    }>
```

#### `afterEmit` hook

```
    AsyncSeriesWaterfallHook<{
      outputName: string,
      plugin: HtmlWebpackPlugin
    }>
```

### Usage:

```js
// If your plugin is direct dependent to the html webpack plugin:
const HtmlWebpackPlugin = require('html-webpack-plugin');
// If your plugin is using html-webpack-plugin as an optional dependency
// you can use https://github.com/tallesl/node-safe-require instead:
const HtmlWebpackPlugin = require('safe-require')('html-webpack-plugin');

class MyPlugin {
  apply (compiler) {
    compiler.hooks.compilation.tap('MyPlugin', (compilation) => {
      console.log('The compiler is starting a new compilation...')

      // Staic Plugin interface |compilation |HOOK NAME | register listener 
      HtmlWebpackPlugin.getHooks(compilation).beforeEmit.tapAsync(
        'MyPlugin', // <-- Set a meaningful name here for stacktraces
        (data, cb) => {
          // Manipulate the content
          data.html += 'The Magic Footer'
          // Tell webpack to move on
          cb(null, data)
        }
      )
    })
  }
}

module.exports = MyPlugin
```

**Comment by swimmadude66** [comment]
Ok, in that case I am pretty sure the plugin is already compatible. I will add a check for the static version number, but right now it does feature detection by the presence of the `getHooks` call:

```typescript
                if (HtmlWebpackPlugin && HtmlWebpackPlugin.getHooks) {
                    // html-webpack 4
                    const hooks = HtmlWebpackPlugin.getHooks(compilation);
                    hooks.alterAssetTags.tapAsync(
                        'NoModulePlugin',
                        (data, cb) => {
                            data.assetTags.scripts = this._transformAssets(data.assetTags.scripts);
                            data.assetTags.styles = this._transformAssets(data.assetTags.styles);
                            data.assetTags.meta = this._transformAssets(data.assetTags.meta);
                            return cb(null, data);
                        }
                    )
                } else {
                    throw new Error('Cannot find appropriate compilation hook');
                }
```

**Comment by jantimon** [comment]
Oh sorry you are right 👍

**Comment by swimmadude66** [comment]
very cool, thanks! By the way, I'm not sure if its related, but I added a test configuration to the travis build to run with `html-webpack-plugin@4.0.0-beta.5` and `webpack@5.0.0-alpha.12` and the tests fail with this error: 
```
Uncaught TypeError: Cannot read property 'add' of undefined
      at childCompilerDependencies.forEach.fileDependency (node_modules/html-webpack-plugin/index.js:142:47)
      at Array.forEach (<anonymous>)
      at compilation.hooks.additionalChunkAssets.tap (node_modules/html-webpack-plugin/index.js:141:35)
      at SyncHook.eval (eval at create (node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
      at SyncHook.lazyCompileHook (node_modules/webpack/node_modules/tapable/lib/Hook.js:156:20)
      at cont (node_modules/webpack/lib/Compilation.js:1332:38)
      at createChunkAssets.err (node_modules/webpack/lib/Compilation.js:1374:6)
      at /home/travis/build/swimmadude66/webpack-nomodule-plugin/node_modules/neo-async/async.js:2825:7
      at done (node_modules/neo-async/async.js:2861:11)
      at /home/travis/build/swimmadude66/webpack-nomodule-plugin/node_modules/neo-async/async.js:2813:7
      at process.nextTick (node_modules/webpack/lib/Compilation.js:2418:52)
      at _combinedTickCallback (internal/process/next_tick.js:132:7)
      at process._tickCallback (internal/process/next_tick.js:181:9)
```

I'm not sure if thats a problem with webpack 5 alpha, an issue with html-webpack-plugin, or an issue with nomodule plugin, but it does looks like something is broken when all 3 play together. I'll keep an eye on webpack 5 development and make sure this plugin works with it once webpack 5 hits an rc or late beta.

**Comment by jantimon** [comment]
Unfortunately Webpack 5 is not supported - we are waiting for support from the webpack team: https://github.com/jantimon/html-webpack-plugin/issues/1129

**Pull request merged**
