### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by skiny2015**
Return includedChunks(In order of the includedChunks) from the compilation result

### CODE REVIEW

**Comment by mastilver** [comment]
Can you explain the purpose of this code?
did you run into an issue?

**Comment by skiny2015** [comment]
Sorry, I didn't explain it before。
When I create multiple pages, the JS order does not follow the specified chunks，I didn't do it with chunksSortMode，So I added a piece of code, and once you specify chunks, you output it in the order chunks。

**Comment by mastilver** [comment]
I don't get why you can't use `chunksSortMode`
You should rely on `filter` to order something

**Comment by skiny2015** [comment]
**My configuration:**
{
    new HtmlWebpackPlugin({
        filename: config.build.assetsRoot + '/pages/console.html',
        template: path.join(__dirname, '.', '../webapp/pages/console.html'),
        inject: true,
        chunks: ['manifest', 'public', 'react', 'console']
    }),
    new HtmlWebpackPlugin({
        filename: config.build.assetsRoot + '/pages/console2.html',
        template: path.join(__dirname, '.', '../webapp/pages/console2.html'),
        inject: true,
        chunks: ['manifest', 'public', 'vue', 'console2']
    })
}
**The result:**
page1:
<script type=text/javascript src=/static/js/console.02dbdc8063b95b346fd6.js></script>
<script type=text/javascript src=/static/js/vue.70601a24c5d766eff054.js></script>
<script type=text/javascript src=/static/js/manifest.78756d18087a5643b1eb.js></script>
<script type=text/javascript src=/static/js/public.588b4a534ea8d7df4c3a.js></script>
page2:
<script type=text/javascript src=/static/js/manifest.78756d18087a5643b1eb.js></script>
<script type=text/javascript src=/static/js/console2.a006b793ea9b9ed33756.js></script>
<script type=text/javascript src=/static/js/react.0351cf0b6ac2c7836187.js></script>
<script type=text/javascript src=/static/js/public.588b4a534ea8d7df4c3a.js></script>
The correct order should be the chunks I configured.
I can't sort correctly using chunksSortMode.  So I added a piece of code, as long as the configuration of the chunks, filter out in accordance with the results of the chunks order.  I don't know if I have a solution. If so, please help me

**Comment by mastilver** [comment]
@skiny2015 Maybe this can help: https://github.com/jantimon/html-webpack-plugin/issues/481#issuecomment-262414169

**Comment by skiny2015** [comment]
I know this method, I used, but only one page is valid, many pages do not work.  My goal is to have pages configured with chunks output in the order of chunks, and I don't know if there are any other ways.

**Comment by jantimon** [comment]
This feature was requested several times - maybe we can modify it a bit to work in a nonbreaking way and introduce it for 3.x

**Comment by skiny2015** [comment]
I expect you to provide the function of specifying the chunks sort.

**Comment by skiny2015** [comment]
I think the code I added is able to solve the order of the specified chunks. I look for it in the order of chunks, and then output the correct result. Of course, you may think more carefully, and my purpose is only to solve my current problems, I hope you can improve this function.

**Comment by mastilver** [comment]
@skiny2015 I may solve it, but I don't think it's the right way

You should edit: https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L332

Add a new `sortMode`, maybe `manual` ( @jantimon , does that sound good?)

When in that mode, just return the array as is

-----
TODO:
- [ ] add tests
- [ ] update documentation

**Comment by skiny2015** [comment]
I did have the option of adding sortMode before, but I found that none had been achieved, so there was no added option

**Comment by jantimon** [comment]
Manuel sounds quite nice 👍 

Also please don't add it to a function which is called filter as your code is not filter releated at all

**Comment by skiny2015** [comment]
Ok.

**Comment by mastilver** [comment]
> I did have the option of adding sortMode before, but I found that none had been achieved, so there was no added option

Yeah, sorry I edited my comment, I initially though `none` would do the job, but it only take webpack output (which has already been altered) and returns it

`manual` need to looks more deeply into webpack stats to make `html-webpack-plugin`' `chunk`, map with either `entries` or `entrypoints` (Those are just pointers, I need to dig more when I have more time)

**Comment by skiny2015** [comment]
I modified my code,  and add a new sortMode. I've tested it on my project.

**Comment by mastilver** [comment]
Would you mind adding some tests like: https://github.com/jantimon/html-webpack-plugin/blob/9b272cfb2bccee98bbe8438c817c4207a0a3cb71/spec/BasicSpec.js#L1380

Also can you update the readme?

I will do a code review later

@jantimon Do you want this to land on `v3.x`?

**Comment by skiny2015** [comment]
Ok, I will

**Comment by skiny2015** [comment]
I failed to add a example,  please tell me how to add the example in webpack2.x.

**Comment by mastilver** [comment]
run:
- `npm i --no-save webpack@2`
- `npm run build-examples`
- `npm i`

**Comment by jantimon** [comment]
What do you think - should we throw an error if chunks is empty and sort mode is manuel?

**Comment by skiny2015** [comment]
Should output empty if  chunks is empty when the sort mode is manual, We can output a warning, but not an exception. What do you think?

**Comment by mastilver** [comment]
@jantimon Sounds like something that should be handle by: https://github.com/jantimon/html-webpack-plugin/issues/675

I still need to work on it, I traveling to France this w-e so I will have plenty of spare time on the boat, I will give it a go

**Comment by jantimon** [comment]
Okay cool

**Comment by kbulis** [comment]
When is the next release? and will it include #481 (new manual chunksSortMode)?

**Pull request merged**
