### PR TITLE
feat(compiler): Use a single compiler for multiple plugin instances

### PR DESCRIPTION
**Pull request by jantimon**
This is a wip proposal to reuse a single compiler for multiple HtmlWebpackPlugin instances.

#962
#965

### CODE REVIEW

**Comment by vhmth** [comment]
@jantimon what's the best way I can incorporate this into my repo for testing? Would love to test build times and get back to you with any weird discrepancies.

**Comment by jantimon** [comment]
```
cd node_modules
git clone https://github.com/jantimon/html-webpack-plugin.git
git checkout feature/cache-file-timestamps
```

**Comment by vhmth** [comment]
@jantimon dopeness!

Went through and it seems like this might be the last thing to land on `webpack-4`? The `webpack-4` branch I take it updates `html-webpack-plugin@next` automatically? If so, can pull from that and try this immediately.

**Comment by jantimon** [comment]
It's not published yet because of #972 but we might ship a new alpha soon 👍

**Comment by vhmth** [comment]
Ack ack!

**Pull request merged**
