### PR TITLE
Initial Webpack3 support

### PR DESCRIPTION
**Pull request by yveskaufmann**
Added initial support for Webpack 3, as descripted in #699. Additionally enabled the ExtractTextPlugin.extract override also for Webpack Version 3.x.x.

The Travis builds for Webpack 3 will still fail. Because the tests & examples depend on the [`appcache-webpack-plugin`](https://github.com/lettertwo/appcache-webpack-plugin) and [`extract-text-webpack-plugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin) which both not  supporting `webpack 3` yet. Fortunately, the webpack 3 support of [`extract-text-webpack-plugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin) is in [progress](https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/540).

### CODE REVIEW

**Comment by jantimon** [comment]
We have to regenerate the examples for webpack 3 to satisfy travis

**Comment by yveskaufmann** [comment]
Yeah, i know but the generation of the examples fails because the installation of webpack@3 and extract-text-webpack-plugin@2.1.2 failed. 

The reason for that are:

```log
355 npm ERR! peerinvalid The package webpack@3.0.0 does not satisfy its siblings' peerDependencies requirements!
356 npm ERR! peerinvalid Peer appcache-webpack-plugin@1.3.0 wants webpack@>=0.11 <2.0.0 || >=2.1.0-beta.13 <3.0.0`

I have changed the travis build to make this obviously.

**Comment by jantimon** [comment]
@yveskaufmann how could we fix that?

**Comment by jantimon** [comment]
Closed because of #707

**Pull request closed without merging**
