### PR TITLE
Feature/webpack 5 merge

### PR DESCRIPTION
**Pull request by jantimon**
Based on #1392 from @fivethreeo

Added travis support for webpack 4 & 5 and new caching manager:

travis

This branch is still work in progress.

### CODE REVIEW

**Comment by jantimon** [comment]
Only two tests are failing for webpack 5:

```
FAIL spec/caching.spec.js
  HtmlWebpackPluginCaching
    ✓ should compile nothing if no file was changed (256ms)
    ✓ should not compile the webpack html file if only a javascript file was changed (64ms)
    ✓ should compile the webpack html file even if only a javascript file was changed if caching is disabled (70ms)
    ✕ should compile the webpack html if the template file was changed (56ms)
    ✓ should not slow down linear (10 plugins should not take 2.5 as much time as a 1 plugin) (87ms)
    ✕ should keep watching the webpack html if only a js file was changed (329ms)
  ● HtmlWebpackPluginCaching › should compile the webpack html if the template file was changed
    expect(received).toBe(expected) // Object.is equality
    Expected: 1
    Received: 0
      192 |         // Verify that only one file was built
      193 |         expect(getCompiledModuleCount(stats.toJson()))
    > 194 |           .toBe(1);
          |            ^
      195 |         // Verify that the html was processed twice
      196 |         expect(htmlWebpackPlugin.evaluateCompilationResult.mock.calls.length)
      197 |           .toBe(2);
      at spec/caching.spec.js:194:12
          at runMicrotasks (<anonymous>)
  ● HtmlWebpackPluginCaching › should keep watching the webpack html if only a js file was changed
    expect(received).toBe(expected) // Object.is equality
    Expected: 3
    Received: 1
      282 |         // Verify that the html was processed trice
      283 |         expect(htmlWebpackPlugin.evaluateCompilationResult.mock.calls.length)
    > 284 |           .toBe(3);
          |            ^
      285 |       })
      286 |       .then(() => compiler.stopWatching())
      287 |       .then(done);
      at spec/caching.spec.js:284:12
          at runMicrotasks (<anonymous>)
```

It looks like it is not recompiling

**Comment by jantimon** [comment]
There is a strange behaviour on node `v12.16.1` with `webpack 4`

**Comment by jantimon** [comment]
Cool thanks for your feedback maybe I can release it as beta :)

**Comment by fivethreeo** [comment]
A alpha/beta would be great 😀

**Pull request merged**
