### PR TITLE
Add fix for failing tests and other bugs for file timestamp based cache

### PR DESCRIPTION
**Pull request by dwoznicki**
### Test fixes
- WebpackRecompilationSimulator does not appear to modify the original file, and therefore does not change the timestamp in `compilation.fileTimestamps` (or at least it doesn't on my machine). I made a temporary monkey-patch fix in [ spec/CachingSpec.js ](spec/CachingSpec.js), but really it belongs in WebpackRecompilationSimulator.

### Bug fixes
- Caching whether the template cache was valid in `HtmlWebpackChildCompiler` was causing html files to rebuild every compilation for me, so I moved it out.
- I found that if I don't clear the child compiler cache every compilation, webpack stops watching my template files. I really have no idea what to make of it, and it's difficult to create tests for since it only seems to happen in `--watch` mode.

All checks run in the following environment.
```
Node.js v8.11.1
linux 4.12.0-041200rc1-generic
npm version 5.6.0
webpack@4.5.0
html-webpack-plugin@3.2.0
```

### CODE REVIEW

**Comment by jantimon** [comment]
Wow thanks could you fix it directly inside https://github.com/jantimon/webpack-recompilation-simulator instead extending a broken version?

Otherwise we would have to maintain the fixes inside the html-webpack-plugin.

Is there any reason for renaming all variables? Imho `needsRebuild` is less accurate than `hasOutDatedTemplateCache`

I having troubles to understand all the changes - why would you introduce `previousCompilationTimestamp` which is now a singleton although there might be multiple child compiler instances?

`needsRebuild` has an sideEffect of clearing the cache. 
I would prefer if a function does only one thing.

I am not sure but did you also remove the vm eval cache?

**Comment by dwoznicki** [comment]
> Wow thanks could you fix it directly inside https://github.com/jantimon/webpack-recompilation-simulator instead extending a broken version?

I can do that, but I'm not sure how to build it, so I put it here to get the tests to pass.

> Is there any reason for renaming all variables? Imho needsRebuild is less accurate than hasOutDatedTemplateCache

Yeah that's also fine. I had just been working on this before you released `feature/cache-file-timestamps`, so I ended up using the variable names I had originally been using on my other branch.

> I having troubles to understand all the changes - why would you introduce previousCompilationTimestamp which is now a singleton although there might be multiple child compiler instances?

I'm not sure I totally understand all the ways this plugin works yet. What would cause there to be multiple child compilers? In any case, I can change it to use a WeakMap instead of a singleton. I do need to track previous compilation timestamps in some way.

> needsRebuild has an sideEffect of clearing the cache.

I can restructure it to be called somewhere in `index.js` probably.

> I am not sure but did you also remove the vm eval cache?

I don't think so, but I'm not totally sure what that is/used for.

Anyway, it's kinda late here, so I'm gonna go to sleep now. Just wanted to get this PR in tonight :]

**Comment by jantimon** [comment]
@dwoznicki I tried to fix the webpack compilation simulator but it seems that the caching logic was changed or is broken:

webpack/webpack/issues/7533

**Comment by dwoznicki** [comment]
@jantimon Ahh, that sucks.
I made some changes to bring things back more in line with the origin branch.

### Notes
- Renamed `needsRebuild` to `hasOutdatedTemplateCache`
  - previously `hasOutdatedTemplateCache` returned **false** if a file dependency was changed (to determine if the child compiler cache needed to be cleared)
  - now it returns **true** if a file dependency was changed (to determine if the html template needs to emitted). 
- Child compiler cache is cleared at the end of every compilation
  - added `childCompiler.clearCachedPromise` to unset compilation promise without unsetting compilation started timestamp
- Moved `hasOutdatedTemplateCache` check into `thisCompilation` hook because `compilation` hook was being called twice per compilation for some reason

**Comment by jantimon** [comment]
Cool I'll look into your changes very soon :)

I have also opened a new pr here https://github.com/jantimon/webpack-recompilation-simulator/pull/2

**Comment by jantimon** [comment]
@sokra told me that caching works only for development - so I adjusted the tests for the webpack-recompilation-simulator and published 2.0.0:

https://www.npmjs.com/package/webpack-recompilation-simulator

**Comment by jantimon** [comment]
@denis-sokolov "Child compiler cache is cleared at the end of every compilation" would require more compilations. Why do we need that?

**Comment by denis-sokolov** [comment]
Wrong mention, @jantimon? I have no idea what you’re talking about.

**Comment by dwoznicki** [comment]
Failing to clear the compiler cache at the end of every compilation causes a strange bug where the file watcher for for HTML template files is removed on subsequent compilations for me. I.e., the compiler stops watching template files.
I'm having trouble creating tests to reproduce this issue since it only occurs in `--watch` mode. Let me try pulling this version of the branch and see if the issue persists.

**Comment by jantimon** [comment]
So webpack keeps track during watching of all files here:

https://github.com/webpack/webpack/blob/4de3ce057d5ce64055fc258505e004d2eccb2cb7/lib/Compiler.js#L146-L147

So we might have to extend the webpack-recompilation-simulator to create reliable unit tests for that case.

**Comment by dwoznicki** [comment]
I'll go ahead and see if I can put together a test in that case.

**Comment by dwoznicki** [comment]
Hey, so I found out what the issue is, but I'm having trouble solving it without clearing the cache at the end of every recompilation. Basically here's what's happening:

1. At the end of every compilation, webpack takes the file dependencies from the compilation object and uses them to determine the watched files. https://github.com/webpack/webpack/blob/8a7597aa6eb2eef66a8f9db3a0c49bcb96022a94/lib/Watching.js#L102-L106
2. The file dependencies of child compilations are also added to the main compilation's file dependencies here. https://github.com/webpack/webpack/blob/e3678aa3767aaeb26ebcf5e3028412bbebdb4f9f/lib/Compilation.js#L1735-L1745
3. Child compilations only get added when `childCompiler.runAsChild` is called. https://github.com/webpack/webpack/blob/e3678aa3767aaeb26ebcf5e3028412bbebdb4f9f/lib/Compiler.js#L227-L245
4. With our current setup, `runAsChild` is not called for cached promises, so the child compilation dependencies (such as the template file) never get added to the file watcher.

I tried caching and the compilation object per child compiler, but it's causing basically all the build stats to be wrong for testing.
I'm still working on this, but it's taking a while atm.

**Comment by jantimon** [comment]
@dwoznicki what about copying the file dependencies (which we store anyway) to the main compilation after each build?

**Comment by dwoznicki** [comment]
@jantimon Hey, couple more changes
### Notes
- No longer clears child compilation each round
- Injects child compilation file dependencies into main compilation file dependencies if template has not changed
  - https://github.com/jantimon/html-webpack-plugin/pull/979/files#diff-168726dbe96b3ce427e7fedce31bb0bcR92
- removed the temp version of webpack-recompilation-simulator, so this branch is now dependent on webpack/loader-utils#115 as well

I've found that these changes work as expected for `--watch` mode in a small test project.

**Comment by jantimon** [comment]
@dwoznicki The webpack-recompilation-simulator does now support watch mode tests: https://github.com/jantimon/webpack-recompilation-simulator#watch-mode

I will release a new version of the webpack-recompilation-simulator once https://github.com/webpack/loader-utils/issues/115 is solved

**Comment by dwoznicki** [comment]
These recent changes to the `feature/cache-file-timesamps` branch cause a ton of conflicts with my version and appears to add a lot of the same functionality. Is there any reason to keep this PR open?

**Comment by jantimon** [comment]
I am not 100% happy with feature/cache-file-timestamps so I might take over some more of your ideas 👍

**Comment by jantimon** [comment]
Thanks again @dwoznicki for all your inputs and work - I merged a lot of it into #972 and will close this for now.

**Pull request closed without merging**
